import {useState} from 'react';
import {people} from './model';
import {customerContext} from './customerContext';
export const visitorSessions=[
 {id:'olivia',live:true,product:'Kanchipuram Silk Saree',cart:89,source:'Instagram',intent:'High',evidence:'Viewed the same product 3 times and added it to cart',seen:'Now'},
 {id:'visitor-060x',live:true,product:'No browsing activity recorded',cart:null,source:'Unknown',intent:'Not enough activity',evidence:'No product interaction recorded',seen:'Now'},
 {id:'ethan',live:false,product:'Forest Silk Saree',cart:110,source:'Instagram',intent:'Medium',evidence:'Viewed a product and asked about another colour',seen:'12 hours ago'}
];
export function Audience({open,visitors=false}:{open:(id:string,conversation?:boolean)=>void;visitors?:boolean}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All');
 const rows=people.filter(p=>(p.name+' '+p.email).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='Customers'&&p.orders>0||filter==='Leads'&&!p.orders&&!customerContext[p.id].anonymous||filter==='Anonymous visitors'&&customerContext[p.id].anonymous));
 const sessions=visitorSessions.filter(v=>(filter!=='Live now'||v.live)&&(filter!=='Earlier today'||!v.live)&&(people.find(p=>p.id===v.id)!.name+' '+people.find(p=>p.id===v.id)!.email).toLowerCase().includes(query.toLowerCase()));
 return <section className="audience"><p className="muted">Sample data · {visitors?'A fixed snapshot, not a live tracking feed.':'Explore identified customers and anonymous shoppers.'}</p><div className="gd-tabs">{(visitors?['All','Live now','Earlier today']:['All','Customers','Leads','Anonymous visitors']).map(t=><button key={t} aria-pressed={filter===t} onClick={()=>setFilter(t)}>{t}{visitors?' · '+(t==='All'?visitorSessions.length:visitorSessions.filter(v=>t==='Live now'?v.live:!v.live).length):''}</button>)}</div><label className="audience-search">{visitors?'Find a visitor':'Find a customer'}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or email"/></label><div className="table-scroll"><table><thead><tr>{(visitors?['Visitor','Viewed product','Cart','Source','Intent / evidence','Last activity','']:['Customer','Contact details','Channel','Orders','Total spent','']).map((t,i)=><th key={i}>{t}</th>)}</tr></thead><tbody>{visitors?sessions.map(v=>{const p=people.find(p=>p.id===v.id)!;return <tr key={v.id}><td><strong>{p.name}</strong><small>{v.live?'Live in sample snapshot':'Session ended'}</small></td><td>{v.product}</td><td>{v.cart===null?'Not recorded':v.cart?'£'+v.cart:'Empty'}</td><td>{v.source}</td><td>{v.intent}<small>{v.evidence}</small></td><td>{v.seen}</td><td><button onClick={()=>open(v.id,true)}>Open conversation</button></td></tr>}):rows.map(p=><tr key={p.id}><td><button onClick={()=>open(p.id)}>{p.name}</button><small>{p.orders?'Shopify customer':!customerContext[p.id].anonymous?'Lead':'Anonymous visitor'}</small></td><td>{p.email||'Email not provided'}<small>{p.phone}</small></td><td>{p.channel}</td><td>{p.orders}</td><td>£{p.spend}</td><td><button onClick={()=>open(p.id,true)}>Open conversation</button></td></tr>)}</tbody></table></div>{!(visitors?sessions.length:rows.length)&&<div className="audience-empty"><h3>No matches found</h3><p>Try another name or clear your filters.</p><button onClick={()=>{setQuery('');setFilter('All')}}>Clear filters</button></div>}</section>
}
