import {useState} from 'react';
import {Card,Badge} from './components';
import {prerequisites,runtime,supported,authorize,type Action} from './rules';
import type {State,Employee,Channel} from './model';
export function Readiness({s,e,patch,knowledge}:{s:State;e:Employee;patch:(p:Partial<State>)=>void;knowledge:()=>void}){
 const issues=prerequisites(s,e);
 return <Card title="Readiness" description="Only this employee’s required prerequisites block activation."><Badge>{issues.length?'Action required':'Ready'}</Badge>{issues.length?<ul>{issues.map(i=><li key={i}>{i}</li>)}</ul>:<p>Required data, knowledge and a supported surface are available.</p>}<p className="muted">Missing FAQs and non-critical policy details are warnings. Unverified answers escalate to a person.</p><button onClick={knowledge}>Review knowledge</button>{!s.widget&&e.id==='maya'&&<button onClick={()=>patch({widget:true})}>Enable widget (demo)</button>}{(s.scenario==='Empty catalogue'||s.activeProducts<1)&&e.id==='maya'&&<button onClick={()=>patch({activeProducts:342,scenario:'Normal',scan:1,running:true})}>Simulate products added &amp; rescan</button>}<details className="setup-details"><summary>Required data and sources</summary>{e.id==='emma'&&<><label className="switch"><input type="checkbox" checked={s.data.carts} onChange={x=>patch({data:{...s.data,carts:x.target.checked}})}/>Checkout/cart data available (demo)</label><label>Reviewed consent / eligibility source<input value={s.data.consentSource} placeholder="Not configured / required before recovery" onChange={x=>patch({data:{...s.data,consentSource:x.target.value}})}/></label><small>A source reference is a prototype placeholder. Production must evaluate the shopper’s eligibility before each message.</small></>}{e.id==='leo'&&<label className="switch"><input type="checkbox" checked={s.data.orders} onChange={x=>patch({data:{...s.data,orders:x.target.checked}})}/>Order data available (demo)</label>}<p>Supported surfaces: {supported(e).join(', ')}. Connect these once in Integrations, then enable employee permissions in Configure.</p></details></Card>
}
export function RoleConfiguration({e,update,save}:{e:Employee;update:(p:Partial<Employee>)=>void;save:()=>void}){
 const fields=e.id==='emma'?[['timing','Recovery timing'],['followup','Follow-up behaviour'],['discountCap','Discount cap'],['policySource','Discount policy source']]:e.id==='leo'?[['lookup','Order lookup behaviour'],['approvals','Approval requirements'],['refundLimit','Refund limit'],['policySource','Refund / exception policy source']]:[['topics','Supported topics'],['escalation','Escalation route'],['tone','Tone / style'],['refundLimit','Refund limit'],['policySource','Refund / exception policy source']];
 return <Card title={'Configure '+e.name} description="Review the role and connected channels. Financial actions remain unavailable without explicit policy authorization."><label>Display name<input value={e.name} onChange={x=>update({name:x.target.value})}/></label><p>{e.description}</p>{e.id==='emma'&&<label className="switch"><input type="checkbox" checked={e.settings.recipientEligible==='yes'} onChange={x=>update({settings:{...e.settings,recipientEligible:x.target.checked?'yes':''},configured:false,previewed:false})}/>Recipient eligibility confirmed for this demo only</label>}{fields.map(([key,label])=><label key={key}>{label}<input value={e.settings[key]||''} placeholder="Not configured" onChange={x=>update({settings:{...e.settings,[key]:x.target.value},configured:false,previewed:false})}/></label>)}<p className="muted">These fields capture configuration for the developer handoff. No timing, discount, refund or eligibility rule is invented or executed. Actions without a configured policy and authorized tool stay blocked.</p><button className="primary" disabled={!e.name.trim()} onClick={save}>Review, save and preview</button></Card>
}
export function Permissions({e}:{e:Employee}){return <section className="permission-summary"><h3>What {e.name} will be allowed to do</h3><div className="table-scroll"><table><thead><tr><th>Action</th><th>{e.mode==='guided'?'Guided':'Full'}</th></tr></thead><tbody><tr><td>Verified low-risk answers / allowed information</td><td>Automatic on permitted channels</td></tr><tr><td>Uncertain answers or unsupported topics</td><td>Escalate to a person</td></tr><tr><td>Financial or policy exceptions</td><td>{e.id==='maya'?'Not permitted for this role':e.mode==='guided'?'Human approval required':'Only within explicit policies and authorized tools'}</td></tr><tr><td>Discount cap</td><td>{e.settings.discountCap||'Not configured / required before discount action'}</td></tr><tr><td>Refund limit</td><td>{e.settings.refundLimit||'Not configured / required before refund action'}</td></tr><tr><td>Policy source / eligibility</td><td>{e.settings.policySource||'Not configured / required before exception action'}</td></tr></tbody></table></div><p className="muted">The model proposes; the platform authorizes. Full never bypasses consent, limits, permissions or escalation. This prototype has no financial executor.</p></section>}
export function RuntimePanel({s,e,patch,update}:{s:State;e:Employee;patch:(p:Partial<State>)=>void;update:(p:Partial<Employee>)=>void}){
 const h=runtime(s,e);const [channel,setChannel]=useState<Channel>(e.channels[0]||supported(e)[0]);const [result,setResult]=useState('');
 const action:Action=e.id==='emma'?'Send recovery message':e.id==='leo'?'Look up an order':e.id==='maya'?'Recommend a product':'Answer a question';
 return <div className="runtime-overview"><div className={'health-strip '+(h.health==='Healthy'?'health-good':'health-warning')}><span className="health-dot"/><div><h2>{h.health==='Healthy'?'Working as expected':h.health==='Paused'?'Automatic actions are paused':'A connection needs attention'}</h2><p>Active · {h.health}</p></div></div>{h.issues.length>0&&<div className="health-explanation"><strong>{h.issues[0]}</strong><p>{h.usable.length?`${h.usable.join(', ')} can keep working. Your setup and history are saved.`:'Your setup and history are saved. Resolve the issue or resume when you’re ready.'}</p>{h.issues.length>1&&<ul>{h.issues.slice(1).map(i=><li key={i}>{i}</li>)}</ul>}</div>}<div className="section-title"><h3>Connected channels</h3><span>{h.usable.length} available</span></div><div className="runtime-channels">{e.channels.map(c=><div className="setting-row" key={c}><span>{c}</span><Badge>{h.usable.includes(c)?'Available':'Stopped'}</Badge>{!s.integrations[c]&&<button onClick={()=>patch({integrations:{...s.integrations,[c]:true},...(c==='Store chat'?{connected:true}:{})})}>Reconnect {c}</button>}</div>)}</div>{e.id==='maya'&&!s.widget&&<button className="primary" onClick={()=>patch({widget:true})}>Enable storefront widget</button>}<div className="runtime-footer"><p>{e.paused?'Resume when you’re ready to help shoppers again.':'Pause automatic actions at any time.'}</p><button onClick={()=>update({paused:!e.paused})}>{e.paused?'Resume employee':'Pause employee'}</button></div><details className="setup-details runtime-demo"><summary>Simulation controls</summary><p className="muted">Prototype only. No messages or external actions are sent.</p>{e.channels.map(c=><button key={c} onClick={()=>patch({integrations:{...s.integrations,[c]:!s.integrations[c]},...(c==='Store chat'?{connected:!s.integrations[c]}:{})})}>{s.integrations[c]?'Disconnect '+c:'Reconnect '+c} (demo)</button>)}{e.id==='maya'&&<button onClick={()=>patch({widget:!s.widget})}>{s.widget?'Disable widget':'Enable widget'} (demo)</button>}<label>Channel<select aria-label="Test channel" value={channel} onChange={x=>setChannel(x.target.value as Channel)}>{supported(e).map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>setResult(authorize(s,e,channel,action).message)}>Simulate: {action}</button><button onClick={()=>setResult(authorize(s,e,channel,e.id==='emma'?'Exceptional discount':'Discretionary refund').message)}>Test financial exception</button>{result&&<p role="status">{result}</p>}</details></div>
}
export function RolePreview({s,e,test}:{s:State;e:Employee;test:()=>void}){
 const [reply,setReply]=useState('');
 const questions=e.id==='emma'?['Preview recovery message','Request an exceptional discount']:e.id==='leo'?['Where is my order?','Request a refund']:['What does the store sell?','Ask about an unverified exchange policy'];
 function ask(q:string){test();setReply(/discount|refund/i.test(q)?'Not configured / required before action. No financial action is executed. Guided requires approval; Full still requires an explicit policy and authorized tool.':e.id==='emma'?'Draft only: “You left an item in your cart. Would you like help?” Sending requires verified recipient consent, channel permission and configured timing.':e.id==='leo'?'Sample order lookup: order #1042 is in transit. In production, the platform must verify identity and retrieve the permitted order before answering.':/exchange/i.test(q)?'I can’t verify that policy. I’ll escalate the question to the store team.':s.knowledge['Store Information'].status==='Ready'?s.knowledge['Store Information'].text:'Required store information is not approved. Ask the team to review it.');}
 return <Card title={e.role+' · Preview & test'} description={e.status==='Active'?'Preview only — no live action is performed.':'Preview only — your AI Employee is not live yet.'}><Badge>{e.id==='emma'?'Email / WhatsApp draft':e.id==='leo'?'Post-purchase conversation':'Support conversation'}</Badge><p>Test a role-specific example. Responses and records are simulated.</p>{questions.map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}{reply&&<p className="ai-message" role="status">{reply}</p>}</Card>
}
